using Aspose.Cloud.Marketplace.Common;
using System;
using System.Collections.Generic;
using Aspose.Cloud.Marketplace.Services.Model.Elasticsearch;
using System.Threading.Tasks;

namespace Aspose.Cloud.Marketplace.App.Middleware
{
    /// <summary>
    /// Application client interface.
    /// </summary>
    public interface IAppClient
    {
        /// <summary>
        /// Request Id (autogenerated)
        /// </summary>
        string RequestId { get; }
        /// <summary>
        /// Application name. App should set this value
        /// </summary>
        string AppName { get; }
        /// <summary>
        /// Statistical data to be logged to access_log
        /// </summary>
        List<StatisticalDocument> Stat { get; set; }
        /// <summary>
        /// Elapsed seconds
        /// </summary>
        double? ElapsedSeconds { get; }
        // 
        /// <summary>
        /// Gets information about error occured
        /// </summary>
        /// <param name="ex">Exception</param>
        /// <returns>Returns HttpStatusCode, error text, error description, binary custom data to be logged</returns>
        ValueTuple<int, string, string, byte[]> ErrorResponseInfo(Exception ex);
    }
    /// <summary>
    /// Application client that can report exceptions
    /// </summary>
    public interface IAppCustomErrorReportingClient : IAppClient
    {
        /// <summary>
        /// Reports an error
        /// </summary>
        /// <param name="doc">Error document</param>
        /// <param name="serviceProvider">service provider</param>
        /// <returns>URL with error data</returns>
        Task<string> ReportException(ElasticsearchErrorDocument doc, IServiceProvider serviceProvider);
    }
}
